Feat: locust
sayakpaul/ml-deployment-k8s-fastapi pull request #31
Opened 2022-03-17 04:09 UTC by deep-diver

2022-03-17 06:31 UTC, sayakpaul commented on locust/locustfile.py
> +class HelloWorldUser(HttpUser):
Let's have a more meaningful name?

2022-03-17 06:32 UTC, sayakpaul commented on locust/README.md
> +         --html report.html
Will `report.html` be generated in the `locust` directory itself? If so, let's add a note about it. 

Also, are you launching the test from your local machine?

2022-03-17 06:33 UTC, sayakpaul requested changes
Minor changes. Once done feel free to merge.

2022-03-17 06:33 UTC, sayakpaul commented on locust/README.md
> +         --html report.html
Also, once the clusters are set up on GKE I think we can share the Locust experiments amongst ourselves. I'd need to know the IPs before that of course.

2022-03-22 06:08 UTC, deep-diver commented on locust/README.md
> +         --html report.html
@sayakpaul 

I have launched locust test in GitHub's codebase VM, and yes `report.html` will be generated in the same directory (but you can manually do this from the locust UI)

2022-03-22 06:12 UTC, sayakpaul commented on locust/README.md
> +         --html report.html
Did you mean Codespace?

2022-03-22 06:12 UTC, deep-diver commented on locust/README.md
> +         --html report.html
ah yes sorry about the typo

2022-03-22 07:00 UTC, sayakpaul reviewed
Clarification needed.

2022-06-11 02:43 UTC, sayakpaul commented
Closing this since Locust load-testing is handled efficiently now. Check `locust` of this repository.

2022-06-11 02:43 UTC, closed without merging